    <div class="row">
        <div class="col-sm-10 js_height overflow js_msglist">
            <?php 
                require("apps/messages.php"); 
            ?>                     
        </div > 
        <div class="col-sm-2 js_height overflow js_userlist">
            <?php 
                require("apps/users.php");
            ?>                     
        </div >   
    </div>
    <div class="row spacing">
        <form method="POST" class="js_input">
            <div class="col-sm-10 nopad">
                <div class="form-group">
                    <label class="sr-only" for="exampleInputMessage">Message</label>
                    <input type="text" name="content" autofocus autocomplete="off" class="form-control intchat" id="exampleInputMessage" placeholder="Message" value="">
                </div>
            </div>
            <div class="col-sm-2">
                <button type="submit" name="action" value="ajout" class="btn btn-default subtchat">Envoyer</button>
            </div>
        </form>
    </div>  