<nav class="navbar navbar-default">
    <div class="container-fluid">                        
        <div class="navbar-header">
            <img class="image-chat" src="public/images/chat.png" alt"chat">
            <a class="titre navbar-brand" href="?page=messages">The minichat</a>
            </div>
            <ul class="nav navbar-nav"></ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="active">
                    <a>Bonjour <?= $_SESSION['pseudo'] ?></a>
                </li>
                <li>
                    <a href="index.php?page=logout">Déconnexion</a>
                </li>                   
            </ul>
        </div>
    </div>
</nav>