<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li><a href="?page=messages">Minichat</a></li>
                    <li><a href="index.php?page=register">Créer mon compte</a></li>
                    <li><a href="index.php?page=logout">Déconnexion</a></li> 
                    <li>Bonjour <?= $_SESSION['pseudo'] ?></li>                   
                </ul>
            </div>
        </div>
    </nav>    
</div>