<div class="header">
    <nav class="navbar navbar-inverse">
        <div class="musik_dream col-xs-12">
            <p><a href="?page=articles">Minichat</a></p>
        </div>
        <div class="row">                        
            <div class="col-sm-12">
                <ul class="nav navbar-nav">
                    <li><a href="index.php">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>    
</div>